name: motorcycle_rental_system

networks:
  container-net:
    name: proxy-mrs-network
    external: false

services:   
  postgres:
    image: postgres
    container_name: mrs.postgres
    hostname: postgres.host.mrs
    
    networks:
      - container-net

    profiles: 
      - prod
      - dev

    ports:
      - "5432:5432"
    
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresPASWD
      POSTGRES_DB: postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: mrs.pgadmin
    user: "root"

    networks:
      - container-net

    profiles: 
      - prod
      - dev
    
    ports:
      - "5180:80"

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com.br
      PGADMIN_DEFAULT_PASSWORD: admin@paswd1234
    
    volumes:
       - ./docker/config/pgadmin/servers.json:/pgadmin4/servers.json
       - ./docker/config/pgadmin/pgpass:/pgadmin4/pgpass 
    
    depends_on:
       - "postgres"
    
    entrypoint: >
      sh -c "
      cp -f /pgadmin4/pgpass /var/lib/pgadmin;
      chmod 600 /var/lib/pgadmin/pgpass;
      /entrypoint.sh"

  app:
    image: motorcycle-rental-system/app
    container_name: mrs.app
    hostname: app.host.mrs

    networks:
      - container-net

    profiles: 
      - prod

    build:
      context: ./src
      dockerfile: web/MotorcycleRentalSystem.Api/Dockerfile
      args:
        - "BUILD_CONFIGURATION=Release"
    
    ports:
      - "5501:5001"
    
    depends_on:
       - "postgres"
       - "pgadmin"

    environment:
      ConnectionStrings__PostgresCNS: Server=postgres.host.mrs;Port=5432;Database=motorcycle-rental-db;User Id=postgres;Password=postgresPASWD;
      AppSettings__UseSwagger: true  