// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotorcycleRentalSystem.Infrastructure.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MotorcycleRentalSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240731133803_Update_v001")]
    partial class Update_v001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MotorcycleRentalSystem.Domain.Entities.Motorcycle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("LicensePlate")
                        .HasColumnType("text");

                    b.Property<long>("ManufacturedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.HasKey("Id");

                    b.ToTable("Motorcycles");
                });

            modelBuilder.Entity("MotorcycleRentalSystem.Domain.Entities.RentOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BeginAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<DateTime>("CreateAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<long>("DeliverymanId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<DateTime>("EstimatedEndAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<DateTime>("ModifiedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<long>("MotorcycleId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric");

                    b.ComplexProperty<Dictionary<string, object>>("FinePlan", "MotorcycleRentalSystem.Domain.Entities.RentOrder.FinePlan#FinePlan", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Days")
                                .HasColumnType("integer");

                            b1.Property<int>("FineType")
                                .HasColumnType("integer");

                            b1.Property<decimal>("PerDay")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Total")
                                .HasColumnType("numeric");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("RentPlan", "MotorcycleRentalSystem.Domain.Entities.RentOrder.RentPlan#RentPlan", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("PerDayCost")
                                .HasColumnType("numeric");

                            b1.Property<int>("PlanPeriod")
                                .HasColumnType("integer");

                            b1.Property<decimal>("TotalCost")
                                .HasColumnType("numeric");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DeliverymanId");

                    b.HasIndex("MotorcycleId");

                    b.ToTable("RentOrders");
                });

            modelBuilder.Entity("MotorcycleRentalSystem.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTime>("ModifiedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MotorcycleRentalSystem.Domain.Entities.AdminUser", b =>
                {
                    b.HasBaseType("MotorcycleRentalSystem.Domain.Entities.User");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("AdminUser");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Administrator",
                            Password = "AQAAAAIAAYagAAAAEIEYZO/oTCCZg1r2Ljcw6bkyTw9Z2Piy131rGVQ0T/IK8WiTg97rPZTCccJMmg9cBw==",
                            UserRole = 2,
                            Username = "admin@admin.com.br"
                        });
                });

            modelBuilder.Entity("MotorcycleRentalSystem.Domain.Entities.DeliverymanUser", b =>
                {
                    b.HasBaseType("MotorcycleRentalSystem.Domain.Entities.User");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.ComplexProperty<Dictionary<string, object>>("DriverLicense", "MotorcycleRentalSystem.Domain.Entities.DeliverymanUser.DriverLicense#DriverLicense", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Number")
                                .HasColumnType("text");

                            b1.Property<string>("Picture")
                                .HasColumnType("text");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");
                        });

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("DeliverymanUser");
                });

            modelBuilder.Entity("MotorcycleRentalSystem.Domain.Entities.RentOrder", b =>
                {
                    b.HasOne("MotorcycleRentalSystem.Domain.Entities.DeliverymanUser", "Deliveryman")
                        .WithMany("RentOrders")
                        .HasForeignKey("DeliverymanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotorcycleRentalSystem.Domain.Entities.Motorcycle", "Motorcycle")
                        .WithMany("RentOrders")
                        .HasForeignKey("MotorcycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deliveryman");

                    b.Navigation("Motorcycle");
                });

            modelBuilder.Entity("MotorcycleRentalSystem.Domain.Entities.Motorcycle", b =>
                {
                    b.Navigation("RentOrders");
                });

            modelBuilder.Entity("MotorcycleRentalSystem.Domain.Entities.DeliverymanUser", b =>
                {
                    b.Navigation("RentOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
